### ISSUE TITLE
Cannot increase heading from level 0 to level 1 with hotkey

### ISSUE THREAD

**Issue by Ktar5** [k4a-l/obsidian-heading-shifter#8]
I cannot increase a heading from level 0 (not having a heading) to level 1 (heading 1) using bound hotkeys. I would like to be able to create a heading with the same hotkey I use to increment the heading.

**Comment by k4a-l** [comment]
Increment is enabled only when a line with some Heading is included.
This is because I think it is natural to perform normal tab behavior (indentation) when there is no Heading.

**Comment by k4a-l** [comment]
Oh, you are talking about a hotkey , not a tab.
In that case, it might be more correct to increment even when no heading

**Comment by k4a-l** [comment]
There is another reason not to increment when there is no heading.

## 1. If all lines not contains with a heading

```markdown
line0
line1
```
it seems to me that it would be better to simply apply a heading

```markdown
# line0
# line1
```

*Currently nothing is happening.


## 2. If lines contains a line with and without a heading
```markdown
# line0
line1
```

What is the correct way to do this
### 1. Increase all of them?
```markdown
## line0
# line1
```

### 2. Increase only the rows that already have a heading?
I think this  is correct.
*This is the current behavior
```markdown
## line0
line1
```

## In some cases, both can be served separately
I would not want to do it because It is not a consistent operation.

**Comment by Ktar5** [comment]
Hey, thanks for the quick reply,
I can see arguments for each, could it possibly be made a toggle in the settings? :)

**Comment by k4a-l** [comment]
I'm sorry, but I'm not willing to implement it.
So if you want it, please implement and PR(or use locally) it 🙏.
